[graph]
all-features = true

[advisories]
version = 2
ignore = [
]

[licenses]
version = 2
allow = [
	"0BSD",
	"Apache-2.0 WITH LLVM-exception",
	"Apache-2.0",
	"BSD-2-Clause",
	"BSD-3-Clause",
	"BSL-1.0",
	"CC0-1.0",
	"ISC",
	"LicenseRef-ring",
	"MIT",
	"MIT-0",
	"MPL-2.0",
	"Unicode-3.0",
	"Unlicense",
	"Zlib",
]

[[licenses.exceptions]]
name = "unicode-ident"
allow = ["Unicode-DFS-2016"]

[[licenses.exceptions]]
# https://github.com/emilk/egui/issues/2321
name = "epaint"
allow = ["OFL-1.1", "LicenseRef-UFL-1.0"]

[[licenses.clarify]]
name = "ring"
expression = "LicenseRef-ring"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "warn"
# Certain crates that we don't want multiple versions of in the dependency tree
deny = [
	{ name = "bevy", deny-multiple-versions = true },
	{ name = "tokio", deny-multiple-versions = true },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# please don't make this list any longer qwq
allow-git = [
	"https://github.com/DCNick3/unsafe-libopus",
	"https://github.com/RobWalt/bevy-trait-query",
	"https://github.com/Schmarni-Dev/Schminput",
	"https://github.com/Schmarni-Dev/bevy_egui",
	"https://github.com/Schmarni-Dev/bevy_web_asset",
	"https://github.com/Schmarni-Dev/opus-rs",
	"https://github.com/awtterpip/bevy_oxr",
	"https://github.com/emilk/ehttp",
]
