# Default settings. Alternative options are commented out.

# Note: When using TLS, we will always send the HSTS header to force clients to only
# use https urls.
[http]
port = 443 # also supports 0 to mean random

# Settings related to configuring TLS certificates. In most cases, the "acme" type is
# the simplest to set up.
[http.tls]
type = "acme" # requires publicly visible port to be 443, otherwise the challenge fails
domains = [] # You must fill this in with your public domain name(s).
is_prod = true # we are using LetsEncrypt's main, production directory.
email = "" # optional: you can fill in your email address here
# domains = ["socialvr.net", "socialvr.net:1337", "10.11.12.13"]

# [http.tls]
# type = "disable" # disables TLS and everything will use HTTP instead.

# [http.tls]
# type = "self_signed"
# domains = ["socialvr.net"]

# [http.tls]
# type = "file"
# cert_path = "path/to/cert.pem"
# private_key_path = "another/path/key.pem"

[third_party.google]
# To get the client id, follow the instructions at:
# https://developers.google.com/identity/gsi/web/guides/get-google-api-clientid#get_your_google_api_client_id
oauth2_client_id = ""

[cache]
# By default, we use the cache directory on your machine (from
# `$XDG_CACHE_HOME/nexus_identity_server` or `~/.config/cache/nexus_identity_server`
# dir = "path/to/my/cache/dir"

