[package]
name = "did-pkarr"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
## Enables IO
io = ["dep:did-pkarr-io"]

[dependencies]
base32 = "0.5.1"
document-features.workspace = true
did-pkarr-io = { path = "./io", optional = true }

[package.metadata.docs.rs]
all-features = true
