name: Nix CI
on:
  workflow_call:
    inputs:
      deploy:
        required: true
        type: boolean

jobs:
  fmt:
    name: Check Nix Formatting
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
    - uses: cachix/cachix-action@v15
      with:
        name: nexus-ci
        # If you chose API tokens for write access OR if you have a private cache
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix develop -c nixpkgs-fmt --check .
