name: Release
on:
  workflow_dispatch:

jobs:
  build:
    name: Build the code for each platform
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.13.0
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2.7.3
      # - name: Install mingw
      #   run: sudo apt-get install -y mingw-w64

      - name: Install cargo-zigbuild
        run: cargo install --locked cargo-zigbuild@0.19.3

      - name: Cargo zigbuild
        run: |
          cargo zigbuild \
              --target x86_64-unknown-linux-musl \
              --target aarch64-unknown-linux-musl \
              --target x86_64-pc-windows-gnu \
              --all
